services:
  group800consumer:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "50051:50051"
    user: root
    restart: always
    image: slgltd/group800consumer:test
    # Optional command for normal run
    command: []
