// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "group800_web/views/components"

func LoginPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body><main class=\"min-h-screen w-full\"><nav class=\"flex w-full border border-b-zinc-200 px-4 py-4\"><h3 class=\"text-base lg:text-lg font-large text-center\">800 Group Ltd\t</h3><img src=\"/logo\" alt=\"Logo\" class=\"ml-auto h-8\"></nav><main class=\"min-h-screen w-full flex items-center justify-center\"><div class=\"w-full max-w-md bg-white p-8 rounded-lg shadow-md\"><h2 id=\"error-message\" class=\"text-red-500 hidden\">Login details were incorrect</h2><h1 class=\"text-2xl font-bold text-gray-700 text-center mb-6\">Sign In</h1><form action=\"/signin\" method=\"POST\"><div class=\"mb-4\"><label for=\"username\" class=\"block text-sm font-medium text-gray-700\">User<span class=\"text-red-500\">*</span></label> <input type=\"text\" id=\"username\" name=\"username\" required class=\"w-full mt-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-teal-500 focus:outline-none\"></div><div class=\"mb-4\"><label for=\"password\" class=\"block text-sm font-medium text-gray-700\">Password<span class=\"text-red-500\">*</span></label> <input type=\"password\" id=\"password\" name=\"password\" required class=\"w-full mt-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-teal-500 focus:outline-none\"></div><button type=\"submit\" class=\"w-full px-4 py-2 bg-gray-500 text-white font-medium rounded-lg hover:bg-gray-600 focus:ring-2 focus:ring-gray-500 focus:ring-offset-2\">Continue</button></form></div></main></main><script>\n\t\t\t\t(function() {\n\t\t\t\t\tconst urlParams = new URLSearchParams(window.location.search);\n\t\t\t\t\tconst loginStatus = urlParams.get('login');\n\t\t\t\t\tif (loginStatus === 'failed') {\n\t\t\t\t\t\tdocument.getElementById('error-message').classList.remove('hidden');\n\t\t\t\t\t}\n\t\t\t\t})();\n\t\t\t</script></body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
